version: '3'
services:
  sitesearch:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - opendistro_security.disabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300